/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f407xx.h"
#include "stm32f407xx_gpio.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//#define RCC_AHB1ENR									((volatile uint32_t*)(RCC_BASE_ADDR + 0x30))
//
//#define GPIOD_MODER									((volatile uint32_t*)0x40020C00)
//#define GPIOD_OSPEEDR								((volatile uint32_t*)(GPIOD_BASE_ADDR + 0x08))
//#define GPIOD_ODR									((volatile uint32_t*)(GPIOD_BASE_ADDR + 0x14))


void delay();

int main(void)
{
	GPIOA_PCLK_EN();
	GPIOD_PCLK_EN();

	GPIO_ModeSel(GPIOD, GPIO_PIN_13, GPIO_OUTPUT);
	GPIO_ModeSel(GPIOA, GPIO_PIN_2, GPIO_ALTERNATE_FUNCTION);
	GPIO_ModeSel(GPIOA, GPIO_PIN_3, GPIO_ALTERNATE_FUNCTION);

	GPIO_SelectAlternateFunction(GPIOA, GPIO_PIN_2, AF7);
	GPIO_SelectAlternateFunction(GPIOA, GPIO_PIN_3, AF7);

	while (1){
		GPIO_WriteToPin(GPIOD, GPIO_PIN_13, SET);
		printf("LED ON\n");
	}
}

void delay(){
	for(int i = 0; i < 900000; i++);
}
