/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define const RCC_BASE_ADDR							0x40023800
#define const RCC_AHB1ENR							(RCC_BASE_ADDR) + (0x30)

#define GPIOD_BASE_ADDR								0x40020C00
#define GPIOD_MODER									0x40020C00

int main(void)
{
	uint32_t *(RCC_AHB1ENR) = (3 << 1);			//EN Clock for GPIOD port (AHB1)
	uint32_t *(GPIOD_MODER) = (24 << 1);
    /* Loop forever */
	for(;;);
}
