M48
; DRILL file {KiCad 9.0.7} date 2026-03-30T10:53:56+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-30T10:53:56+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.400
%
G90
G05
T1
X70.47Y-37.01
X70.47Y-166.48
X163.34Y-37.01
X163.34Y-166.36
T2
X143.94Y-47.81
M30
